# 配置数据源
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url:  jdbc:mysql://localhost:3306/ssmtest?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        maxActive: 2335
        maxIdel: 120
        maxWait: 100
    # JSP
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

# log4j2 日志
logging:
    config:
      classpath: log4j2.xml

# Mybatis 配置
mybatis:
    typeAliasesPackage: com.xuwc.learn.models
    mapperLocations: classpath:mapper/*.xml

security:
  oauth2:
    client:
      client-id: 98169db825c8c894c8f4
      client-secret: b5c251f9e2045ab87f6e362389172fc4c1d1df3e
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
#      registered-redirect-uri: http://www.xuwc.com:8080/github_login
      use-current-uri: false
    resource:
      userInfoUri: https://api.github.com/user
#    sso:
#      login-path: /github_login


## THYMELEAF (ThymeleafAutoConfiguration)
##开启模板缓存（默认值：true）
#spring.thymeleaf.cache=false
##Check that the template exists before rendering it.
#spring.thymeleaf.check-template=true
##检查模板位置是否正确（默认值:true）
#spring.thymeleaf.check-template-location=true
##Content-Type的值（默认值：text/html）
#spring.thymeleaf.content-type=text/html
##开启MVC Thymeleaf视图解析（默认值：true）
#spring.thymeleaf.enabled=true
##模板编码
#spring.thymeleaf.encoding=UTF-8
##要被排除在解析之外的视图名称列表，用逗号分隔
##spring.thymeleaf.excluded-view-names=
##要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
##spring.thymeleaf.mode=HTML5
##在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
#spring.thymeleaf.prefix=classpath:/templates/
##在构建URL时添加到视图名称后的后缀（默认值：.html）
#spring.thymeleaf.suffix=.html
##Thymeleaf模板解析器在解析器链中的顺序。默认情况下，它排第一位。顺序从1开始，只有在定义了额外的TemplateResolver Bean时才需要设置这个属性。
##spring.thymeleaf.template-resolver-order=
##可解析的视图名称列表，用逗号分隔
##spring.thymeleaf.view-names=

# JPA 配置
## Specify the DBMS
#spring.jpa.database = MYSQL
## Show or not log for each sql query
#spring.jpa.show-sql = true
## Hibernate ddl auto (create, create-drop, update)
#spring.jpa.hibernate.ddl-auto = none
## Naming strategy
#hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


